import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/custom-bootstrap.scss"; 

import { Container } from "react-bootstrap";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Container fluid className="p-4 bg-light">
          {children}
        </Container>
      </body>
    </html>
  );
}
